### ISSUE TITLE
Suggestion: Select/Filter what is displayed

### ISSUE THREAD

**Issue by ShagoY** [Renaud11232/OctoPrint-Resource-Monitor#1]
It would be nice to be able to filter the display, for example remove the network lo and/or Lan when I use only wifi (wlan).

**Comment by Renaud11232** [comment]
Hello,

I'll look into adding this when I have some spare time.
I'm still not shure what would the best/cleanest way of doing it, but I didn't really had the time to think about this.

**Comment by Renaud11232** [comment]
Hello,

Just to give an update.
I've done some modifications to the plugin that adds a way to select which network intefaces and which disks to filter out.
This is not released yet and needs further testing.

![image](https://user-images.githubusercontent.com/13933802/71598550-8c9d1a80-2b47-11ea-831f-135144cff7f3.png)

**Comment by tmagis** [comment]
![image](https://user-images.githubusercontent.com/35865709/71788358-bcee2880-3021-11ea-9b96-fe7afb31cfc6.png)
