### ISSUE TITLE
Wrong CPU/Processor data on Windows plattform

### ISSUE THREAD

**Issue by LMS0815** [Renaud11232/OctoPrint-Resource-Monitor#12]
The processor usage seems to be 3 times higher than the data MS Task-Manager is reporting. Processor speed seems to be slightly higher.
![Anmerkung 2020-07-12 162617](https://user-images.githubusercontent.com/8235214/87248943-7a882700-c45c-11ea-9076-10d2826f7974.png)

Environment: Python 2.7

**Comment by Renaud11232** [comment]
Hello,

Both problems you are facing come from the library (`psutil`) i use to get the current resource usages.
While most of the features work on WIndows, they might not be as accurate as on Linux.

In the `psutil` documentation :
> On Linux current frequency reports the real-time value, on all other platforms it represents the nominal “fixed” value.

This might explain the difference you are seeing.

For that same reason it is impossible (with `psutil`) to get the CPU temperature.

I don't think there is anything I can do against that without using another library or writing Windows specific code.
