### ISSUE TITLE
The temperature tab is missing

### ISSUE THREAD

**Issue by DjBac** [Renaud11232/OctoPrint-Resource-Monitor#17]
The temperature tab on a Pi 4 (latest octoprint) is missing.

**Comment by Renaud11232** [comment]
Hello,

Could you please provide your OctoPrint logs.
In addition to that, can you try running the following command on your Raspberry : 
```bash
/home/pi/oprint/bin/python -c "import psutil; print(psutil.sensors_temperatures())"
```
And give me the output.
