### ISSUE TITLE
Temperature in Fahrenheit

### ISSUE THREAD

**Issue by natron734** [Renaud11232/OctoPrint-Resource-Monitor#18]
Would it be possible to show Temperature tab in F?

**Comment by Renaud11232** [comment]
Hello,

I just created a new release candidate that adds Fahrenheit conversion ([0.2.6rc2](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/releases/tag/0.2.6rc2))
It's not available through OctoPrint's automatic updates yet, but you can install it manually if you want to test it.

If you do so, can you report if that worked well ?

Thanks

**Comment by natron734** [comment]
In installed 0.2.6rc2 and the Resource Monitor tab is no longer displayed. Note: I am using Python 3, and I disabled Themeify Plugin as additional testing. Reinstalled 0.2.6rc2 and still no Resource Monitor tab is displayed.

**Comment by Renaud11232** [comment]
Can you provide the logs so I can look into the issue ?

**Comment by natron734** [comment]
[plugin_pluginmanager_console.log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/5319326/plugin_pluginmanager_console.log)

**Comment by natron734** [comment]
I hope that's the log you're looking for. Thanks again!

**Comment by Renaud11232** [comment]
Can you also provide `octoprint.log` ?

Thanks

**Comment by natron734** [comment]
[octoprint.log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/5321573/octoprint.log)

**Comment by Renaud11232** [comment]
Hello,

Thanks for the logs, I think I found the issue.
This should now be fixed in [0.2.6rc3](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/releases/tag/0.2.6rc3)
