### ISSUE TITLE
Feature request: Temperature

### ISSUE THREAD

**Issue by mittkonto** [Renaud11232/OctoPrint-Resource-Monitor#2]
Love this plugin!
Would be awesome though if it could monitor temperature as well!

"cat /sys/devices/virtual/thermal/thermal_zone0/temp"
Gives: 57000 = 57c

**Comment by skohls** [comment]
I second this request.

Some other options:

pi@octopi:~ $ cat /sys/class/thermal/thermal_zone*/temp
40894

pi@octopi:~ $ vcgencmd measure_temp
temp=39.0'C

pi@octopi:~ $ /opt/vc/bin/vcgencmd measure_temp | tr -d "temp=" | tr -d "'C"
40.0

All taken within a few seconds - so there are some differences between them but for the purpose of this plugin they all should be ok as a data source.

**Comment by Renaud11232** [comment]
Hello,
I'm glad you like the plugin :)

I will probably add this when I have the time.
Thanks for giving different ways of implementing this.

While these methods will likely work fine, they are linux specific, or even Raspberry specific and I want the plugin to be compatible with any OS.

`psutil` (the library I use to get resource usage) does provide a way of getting temperature sensors, that's probably how I'll end up doing it.

Thanks anyway for the advice :)

**Comment by Renaud11232** [comment]
Hello,

Quick little update on this.
I've added the CPU temperature in the CPU tab.
I still need to test it on a Raspberry Pi before releasing it.
![image](https://user-images.githubusercontent.com/13933802/71669550-47f2c880-2d6d-11ea-8afe-5a971c4e6c33.png)

**Comment by skohls** [comment]
Thanks, really looking forward to this!

**Comment by tmagis** [comment]
![image](https://user-images.githubusercontent.com/35865709/71788350-a3e57780-3021-11ea-8775-6c587367bee0.png)
