### ISSUE TITLE
no data is shown in charts

### ISSUE THREAD

**Issue by jkhyper** [Renaud11232/OctoPrint-Resource-Monitor#29]
since I've updated the plugin to the latest 0.3.0 release, no data is shown in the graphs or elsewhere on the Resoure Monitor tab.
<img width="636" alt="Screenshot 2021-02-08 at 17 42 02" src="https://user-images.githubusercontent.com/78749988/107251719-f66b4180-6a34-11eb-900a-331095c585ea.png">

**Comment by Renaud11232** [comment]
Hello,

Could you please provide the octoprint logs as well as the browser console logs (On Google Chrome, press F12)

Thanks

**Comment by mmatesic01** [comment]
I can also confirm that with version 0.3.0. Previous version worked fine.

**Comment by Renaud11232** [comment]
Hello,

Could you please provide the octoprint logs as well as the browser console logs (On Google Chrome, press F12)

Thanks

**Comment by mmatesic01** [comment]
I've just re-enabled my Resource monitor again and for some strange reason it works now. 
Could it be the bowser cache that I cleared lately?

**Comment by Renaud11232** [comment]
It is possible but I can't be 100% sure

**Comment by jghake** [comment]
I'm having the same issue. I cleared local files in Chrome but I haven't tried disabling the plug-in yet.

**Comment by Kenjekenny** [comment]
Had the same issue after updating to version 0.3.0. After updating another plugin (DisplayLayerProgress) and rebooting octoprint, resource monitor suddenly started working again (previous reboots had no effect).

**Comment by farbefreak** [comment]
I do have the same problem. After the Update there is no data displayed. 
I read this thread, so I disabled the plugin, restarted, enabled, restarted -> problem gone.
However after another restart, the data is again not displayed. -> Browser data clearing does not help. 
Only disabling and reenabeling does work.

**Comment by Renaud11232** [comment]
I do understand that this seems to be an issue affecting multiple people.
But, as I said, in previous messages, I need the logs from octoprint and the JS console in order to start investigating.

The issue does not seem to happen on my OctoPrint instance, so without those logs I currently have no idea what the issue might be.

Thanks

**Comment by farbefreak** [comment]
i am happy to provide logs, however i need to know what you need. i am a beginner, so i don't know what JS console means. Are you referring to something inside the browser or do i get it out of the PI?

**Comment by Renaud11232** [comment]
Everything should be available from the browser.

The logs from OctoPrint can be retrieved from the settings:
![image](https://user-images.githubusercontent.com/13933802/107823779-a5cf4d80-6d80-11eb-8924-9d1f7ecd2b89.png)

To get the logs from the JS console, From Google Chrome you can press F12, there should be a "Console" tab.
You can copy paste or take a screenshot of what's there.
![image](https://user-images.githubusercontent.com/13933802/107824067-1aa28780-6d81-11eb-94d4-3fb451a9c67d.png)

I'm not sure the F12 shortcut works on other browsers but you can also get there by right-clicking anywhere and selecting "Inspect element" then going in the console tab.

Thanks

**Comment by jgugler** [comment]
I'm having the same issue since a couple of days. Here are the logs and the console
[octoprint.log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/5974415/octoprint.log)
![Screenshot 2021-02-12 at 22 49 58](https://user-images.githubusercontent.com/11466344/107826159-b1247800-6d84-11eb-8299-72d8289f5b70.png)

**Comment by Renaud11232** [comment]
Thanks,

I didn't find any relevant error in `octoprint.log`. The logs from the browser however showed an error from my plugin.

I just created a prerelease that should address this issue, it won't automatically update but you can install it manually through the plugin manager using this url : [https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/0.3.1rc1.zip](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/0.3.1rc1.zip)

Can you test it and tell if that fixed the issue ?

Thanks

**Comment by jgugler** [comment]
Just installed it and after restarting it works again! Thanks

**Comment by Renaud11232** [comment]
Thanks
@jkhyper @mmatesic01 @jghake @Kenjekenny @farbefreak
Can you also check that it's fixed for you as well ?

Thanks

**Comment by jghake** [comment]
Looks like mines working

**Comment by Kenjekenny** [comment]
Resource monitor stopped working again after reboot but after installing your bugfix its working again, even after numerous reboots. Thx alot!

**Comment by farbefreak** [comment]
I did install it and its working!

Many many thanks for your work!

**Comment by Renaud11232** [comment]
The fix for this issue is now released in version 0.3.1 that should be available directly in OctoPrint.

**Comment by jkhyper** [comment]
> The fix for this issue is now released in version 0.3.1 that should be available directly in OctoPrint.

Thank you for the fast followup and support. With 0.3.1 all data is shown again. Also thanks for maintaining a useful plugin!
