### ISSUE TITLE
Temperature graph

### ISSUE THREAD

**Issue by wi1k1n** [Renaud11232/OctoPrint-Resource-Monitor#3]
It is probably a good idea to have a screen with cpu temperature graph (for raspberry pi it is `vcgencmd measure_temp` command).

This might be helpful to debug parameters (e.g. temperature thresholds) of active cooling for RPi. For example in my setup RPi is controlled by GPIO and I'm not 100% sure if my parameters are optimal (i.e. produce least noise with highest cooling performance). Having this graph could help me finetune cooling setup.

**Comment by Renaud11232** [comment]
Hello,
While waiting for the graph to be added, the temperature should already be monitored in the Processor section.
![processor tab](https://user-images.githubusercontent.com/13933802/71669550-47f2c880-2d6d-11ea-8afe-5a971c4e6c33.png)

**Comment by wi1k1n** [comment]
Yes, sure, thank you

**Comment by Renaud11232** [comment]
This is released in 0.2.1
