### ISSUE TITLE
Y-axis labels

### ISSUE THREAD

**Issue by jmsaltzman** [Renaud11232/OctoPrint-Resource-Monitor#30]
Y-axis labels for the graphs would be very useful! Processor could be assumed to be a 100% scale, but temperature, memory, disk, and network graphs are meaningless without Y-axis values.

Labels of min and max values would be awesome.

**Comment by Renaud11232** [comment]
This was added in 0.3.2 released just now

**Comment by jmsaltzman** [comment]
Awesome thank you!
