### ISSUE TITLE
[FR] Display both permanent and temporary IPv6 addresses when available.

### ISSUE THREAD

**Issue by knugrone** [Renaud11232/OctoPrint-Resource-Monitor#35]
When the OctoPrint server is on a network with IPv6 using SLAAC with privacy addition it generates 2 IPv6 adresses. One based on MAC adress and one short lived temporary random adress. Currently the Resource Monitor just displays the temporary adress. For local use the Link Local adress would be usefull (the one starting with fe80) this also is based on the MAC adress of the interface.

**Comment by Renaud11232** [comment]
Hello,

0.3.6 is now released.
It will now display all IP adresses.
