### ISSUE TITLE
[BUG] Temperature not showing on Orangepi Zero2

### ISSUE THREAD

**Issue by 7R0J4Ner** [Renaud11232/OctoPrint-Resource-Monitor#41]
**Describe the bug**

The temperature of the Orangepi is not displayed.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/45797323/208289029-1d7c0cd0-3189-4e0b-b940-25ea500ec789.png)

**Version of OctoPrint-Resource-Monitor**

0.3.9
Installed using pluginmanager

**Server configuration**
 - OS: Linux 4.9.170-sun50iw9
 - Browser Firefox 108.0.1 (64-Bit)

**OctoPrint logs with `octoprint.plugins.resource_monitor` set to DEBUG**

https://www.dropbox.com/t/qNAYccVjY2FCQxId

**Comment by Renaud11232** [comment]
Hello,

I just released 0.3.10 which should now display OPi Zero 2 CPU temperature.

**Comment by 7R0J4Ner** [comment]
Wow, that was Fast.
Works perfectly.
Thanks a lot!
