### ISSUE TITLE
[FR] Support for AMLogic temperatures

### ISSUE THREAD

**Issue by mlask** [Renaud11232/OctoPrint-Resource-Monitor#45]
Resource Monitor plugin works perfectly fine on Odroid C1+ except it doesn't show CPU temperature.

An easy fix would be adding `"aml_thermal"` to `temperature_possible_keys`, but the catch is that temperatures are read as fractions, so additional conversion has to be made:
```
cpu_temp = temp[key][0]._asdict()
if key == "aml_thermal":
	for _k in cpu_temp:
		cpu_temp[_k] *= 1000
```

I've got it working on my device, but maybe it would be helpful for others.

**Comment by Renaud11232** [comment]
Hello,

This is now included in release 0.3.15
