### ISSUE TITLE
[BUG] Plugin does not work on Octo4a

### ISSUE THREAD

**Issue by kdobrev** [Renaud11232/OctoPrint-Resource-Monitor#49]
**Describe the bug**

**To Reproduce**

Install plugin on Octo4a

**Expected behavior**

Have resources displayed

**Screenshots**

**Version of OctoPrint-Resource-Monitor**

What version are you using, how was it installed ?

**Server configuration**
 - OS: Android
 - Python version [e.G. 2.7, 3.6, ...]

**OctoPrint logs with `octoprint.plugins.resource_monitor` set to DEBUG**

Upload your logs here

**Browser console logs**

Upload the logs of your browser here, on Chrome press F12 and go in the console tab

**Comment by Renaud11232** [comment]
Hello,

While I can't tell for sure since you did not provide the needed logs, I assume this is the same problem as #40.

Because of Android being so restrictive about file permissions, I don't think there is any way to fix this.
