### ISSUE TITLE
Adding UPS support

### ISSUE THREAD

**Issue by gshlomi** [Renaud11232/OctoPrint-Resource-Monitor#5]
Hi.
Thanks for your great work.
Can you please consider adding support to display UPS status, either from APCUPSD or NUT packages?
Showing information like UPS load, battery remaining time and stuff like that.

Thanks

**Comment by Renaud11232** [comment]
Hello,
I'm glad you like the plugin.

Sadly, I don't think this will make it into the plugin, for multiple reasons :

First, I don't have any UPS, so adding this would have to be done blindly without being able to test it.
Then I feel that this is a bit out of the scope of my plugin, which gives general information about resource usage on the OctoPrint host. And having OctoPrint running off an UPS is already a very specific use case.
Finally, I don't know packages you mentionned (or any alternative).

This might have its place in another plugin, by someone that knows more about UPSes than me.

Sorry, I hope you understand.
