### ISSUE TITLE
Feature request: Sidebar support?

### ISSUE THREAD

**Issue by Bootscreen** [Renaud11232/OctoPrint-Resource-Monitor#8]
Hello,

is it possible to get a version for the Sidebar?

**Comment by Renaud11232** [comment]
Hello,

It is possible, and it's quite a good idea.
But I currently don't have the time

I will look into adding this when possible

**Comment by Renaud11232** [comment]
Hello,

I've been thinking of different ways to implement this, but I can't think of a "pretty" way to add this in without making it useless because of the small size of the sidebar.
